// This module will contain the gRPC stubs generated by tonic_build
pub mod gen {
    // Assuming the package definition in your .proto file is:
    // package influxdb3.internal.replication.v1;
    // tonic will generate a module based on this package name.
    // The actual generated filename will be `influxdb3.internal.replication.v1.rs`
    // inside the `src/gen` directory.
    tonic::include_proto!("influxdb3.internal.replication.v1");
    tonic::include_proto!("influxdb3.internal.distributed_query.v1"); // Added
}

// Optional: Re-export the generated types for easier access from other crates.
// This creates a more ergonomic API for users of this proto crate.
pub mod influxdb3 {
    pub mod internal {
        pub mod replication {
            pub mod v1 {
                pub use crate::gen::{
                    replication_service_client as GrpcReplicationServiceClient, // Alias to avoid name clash if re-exporting multiple clients
                    ReplicationServiceClient,
                    ReplicateWalOpRequest,
                    ReplicateWalOpResponse,
                };
                pub use crate::gen::{
                    ReplicationService,
                    ReplicationServiceServer,
                };
            }
        }

        pub mod distributed_query {
            pub mod v1 {
                pub use crate::gen::{
                    distributed_query_service_client as GrpcDistributedQueryServiceClient, // Alias
                    DistributedQueryServiceClient,
                    ExecuteQueryFragmentRequest,
                    ExecuteQueryFragmentResponse,
                };
                pub use crate::gen::{
                    DistributedQueryService,
                    DistributedQueryServiceServer,
                };
            }
        }
    }
}
