// This module will contain the gRPC stubs generated by tonic_build
pub mod gen {
    // Assuming the package definition in your .proto file is:
    // package influxdb3.internal.replication.v1;
    // tonic will generate a module based on this package name.
    // The actual generated filename will be `influxdb3.internal.replication.v1.rs`
    // inside the `src/gen` directory.
    tonic::include_proto!("influxdb3.internal.replication.v1");
}

// Optional: Re-export the generated types for easier access from other crates.
// This creates a more ergonomic API for users of this proto crate.
pub mod influxdb3 {
    pub mod internal {
        pub mod replication {
            pub mod v1 {
                pub use crate::gen::{
                    replication_service_client, // Client struct: ReplicationServiceClient
                    ReplicationServiceClient,   // Alias for convenience if needed, or rely on full path
                    ReplicateWalOpRequest,
                    ReplicateWalOpResponse,
                    // Add other request/response types generated if any
                };

                // Re-export server traits if this crate is also used by servers
                // (which it is, as per build.rs)
                pub use crate::gen::{
                    ReplicationService,         // Service trait: ReplicationService
                    ReplicationServiceServer,   // Server struct: ReplicationServiceServer
                };
            }
        }
    }
}
